package zhuke.manong.community.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userss.id
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userss.account_id
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userss.name
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userss.token
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userss.gmt_create
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userss.gmt_modified
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userss.avatar_url
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userss.type
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userss.id
     *
     * @return the value of userss.id
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userss.id
     *
     * @param id the value for userss.id
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userss.account_id
     *
     * @return the value of userss.account_id
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userss.account_id
     *
     * @param accountId the value for userss.account_id
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userss.name
     *
     * @return the value of userss.name
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userss.name
     *
     * @param name the value for userss.name
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userss.token
     *
     * @return the value of userss.token
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userss.token
     *
     * @param token the value for userss.token
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userss.gmt_create
     *
     * @return the value of userss.gmt_create
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userss.gmt_create
     *
     * @param gmtCreate the value for userss.gmt_create
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userss.gmt_modified
     *
     * @return the value of userss.gmt_modified
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userss.gmt_modified
     *
     * @param gmtModified the value for userss.gmt_modified
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userss.avatar_url
     *
     * @return the value of userss.avatar_url
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userss.avatar_url
     *
     * @param avatarUrl the value for userss.avatar_url
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userss.type
     *
     * @return the value of userss.type
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userss.type
     *
     * @param type the value for userss.type
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}