package zhuke.manong.community.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;
import zhuke.manong.community.model.User;
import zhuke.manong.community.model.UserExample;
/********************************************************************************
 * Purpose: 映射 mapper 中 用户操作相关 SQL 的接口
 * Author: Caijinbang
 * Created Date:2021-10-29
 * Modify Description:
 * 1. 新增映射 mapper 中 用户操作相关 SQL 方法 (Caijinbang 2021-10-29)
 ** *****************************************************************************/
@Mapper
@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userss
     *
     * @mbg.generated Mon Feb 28 14:51:48 CST 2022
     */
    int updateByPrimaryKey(User record);
}